DROP DATABASE if exists TryMyEWallet;
CREATE DATABASE TryMyEWallet;
USE  TryMyEWallet;

CREATE TABLE RET_SHOP_DETAILS(
    RET_SHOP_ID INTEGER(5) AUTO_INCREMENT,
    RET_SHOP_NAME VARCHAR(50) NOT NULL,
    RET_CONTACT INTEGER(10) ,
    RET_ADDRESS VARCHAR(50) NOT NULL,
    RET_CITY VARCHAR(15) NOT NULL,
    RET_PINCODE INTEGER(6) NOT NULL,
    RET_STATE VARCHAR(15) NOT NULL,
    RET_BAL DECIMAL(7, 3) NOT NULL, 
	primary key ( RET_SHOP_ID )
);


CREATE TABLE RET_DETAILS(
	RET_EMAIL VARCHAR(50),
	RET_PASSWORD VARCHAR(50) NOT NULL,
	RET_ENABLED INTEGER(1) NOT NULL,
	RET_NAME VARCHAR(50) NOT NULL,
    RET_MOBILE VARCHAR(10) NOT NULL,
    RET_ROLE VARCHAR(10) NOT NULL,
    RET_SHOP_ID INTEGER(5),
    RET_PAN VARCHAR(20) NOT NULL,
    RET_AADHAAR VARCHAR(20) NOT NULL,
    RET_GST VARCHAR(20) NOT NULL,

	primary key ( RET_EMAIL ),
    FOREIGN KEY ( RET_SHOP_ID ) REFERENCES RET_SHOP_DETAILS(RET_SHOP_ID)
);

INSERT INTO RET_SHOP_DETAILS ( RET_SHOP_NAME, RET_CONTACT,RET_ADDRESS,RET_CITY,RET_PINCODE,RET_STATE) VALUES ( "Shop1", 1234, "Add1","Mumbai",401203, "Maharashtra");
INSERT INTO RET_SHOP_DETAILS ( RET_SHOP_NAME, RET_CONTACT,RET_ADDRESS,RET_CITY,RET_PINCODE,RET_STATE) VALUES ( "Shop2", 1234, "Add2","Mumbai",401203, "Maharashtra");
INSERT INTO RET_SHOP_DETAILS ( RET_SHOP_NAME, RET_CONTACT,RET_ADDRESS,RET_CITY,RET_PINCODE,RET_STATE) VALUES ( "Shop3", 1234, "Add3","Mumbai",401203, "Maharashtra");
INSERT INTO RET_SHOP_DETAILS ( RET_SHOP_NAME, RET_CONTACT,RET_ADDRESS,RET_CITY,RET_PINCODE,RET_STATE) VALUES ( "Shop4", 1234, "Add4","Mumbai",401203, "Maharashtra");

INSERT INTO RET_DETAILS (RET_EMAIL ,RET_PASSWORD, RET_ENABLED, RET_NAME, RET_MOBILE, RET_ROLE, RET_SHOP_ID,RET_PAN,RET_AADHAAR,RET_GST) VALUES ('tom1@infosys.com', 'Tom@123', ,  "TOM1","7021068993","ADMIN", 1,"PAN","AADHAR","GST");
INSERT INTO RET_DETAILS (RET_EMAIL ,RET_PASSWORD, RET_ENABLED, RET_NAME, RET_MOBILE, RET_ROLE, RET_SHOP_ID,RET_PAN,RET_AADHAAR,RET_GST) VALUES ('tom2@infosys.com', 'Tom@123', 1,  "TOM2","7021068993","ADMIN", 2,"PAN","AADHAR","GST");
INSERT INTO RET_DETAILS (RET_EMAIL ,RET_PASSWORD, RET_ENABLED, RET_NAME, RET_MOBILE, RET_ROLE, RET_SHOP_ID,RET_PAN,RET_AADHAAR,RET_GST) VALUES ('tom3@infosys.com', 'Tom@123', 1, "TOM3","7021068993","USER",  3 ,"PAN","AADHAR","GST");
INSERT INTO RET_DETAILS (RET_EMAIL ,RET_PASSWORD, RET_ENABLED, RET_NAME, RET_MOBILE, RET_ROLE, RET_SHOP_ID,RET_PAN,RET_AADHAAR,RET_GST) VALUES ('tom4@infosys.com', 'Tom@123', 1, "TOM4","7021068993","USER",  4 ,"PAN","AADHAR","GST");


commit;


